### ISSUE TITLE
STAT Axis Value tables: allowing for both ranges & style linking

### ISSUE THREAD

**Issue by sairuspatel** [MicrosoftDocs/typography-issues#576] opened 2020-08-31 23:20 UTC
(The content of this feedback is copied from my email to mpeg-otspec Aug 26, 2020, archived here: https://lists.aau.at/pipermail/mpeg-otspec/2020-August/002142.html)

Greetings, all.
 
Here’s a proposal I brought up on the OTFontVar list a month or so ago. (The concern has been discussed on that list before.) I’ve reworked the proposal slightly. There hasn’t been additional feedback in the past few weeks, and I hope we can somehow declare this resolved soon.
 
 
=== Background & concern ===
 
STAT (https://docs.microsoft.com/en-us/typography/opentype/spec/stat#axis-value-tables) says, of Axis Value tables, “No two tables should provide information for the same axis value.”
 
Perhaps that was intended for Axis Value tables *of the same format*. Certainly there are compelling cases where formats 2 & 3 would be needed or appropriate for the same axis value (example below).
 
The concern is that at least one font validation tool warns about such fonts due to the above stricture in the spec. It’s conceivable that implementations may reject such fonts or ignore some of their Axis Value tables because of the perceived violation.
 
Example:
 
In a variable font, Axis Value format 2 for wght=400 (range 350–450) assigns name “Regular” and format 3 for wght=400 provides the bold style-link (to 700). Adobe has made some variable fonts in this way, and I hear other foundries are doing so as well. I know that opsz was an important use case for format 2, so just to be clear, the idea behind assigning a name to a weight range (just as to an opsz range, though opsz ranges also allow for automatic selection) is allowing apps to choose to make custom instance names more human-readable, e.g. “Wide Light-299” as in Photoshop instead of something like “Wide 299” or “Wide wght-299”, for the case when the user started from the “Wide Light” named instance and reduced the weight by just a single unit. Users shouldn’t be expected to know what numerical weight values mean and apps shouldn’t need to make hard-coded assumptions about UI names: a font should be able to specify these strings. Indeed, specifying such strings are a big part of what the STAT table is about.
 
 
=== Solution ===
 
Replace “No two tables should provide information for the same axis value” with:
 
>No two tables of the same format should provide information for the same axis value or (in the case of format 4) combination of axis values. In the case where different format tables, for formats 1–3, provide information for the same axis value, the value of their flags field as well as of their valueNameID field must be the same. A format 4 table may specify an axis value that is also specified in another table, but only if there is some other difference in the axis values specified by those tables. Note that the term “axis value” in this paragraph refers only to the ‘value’ field in formats 1, 3, and 4, and the ‘nominal value’ field in format 2.

 
The first & third sentences in the above proposal are based on Peter Constable’s suggestion on the OTFontVar list when I brought up this topic. Peter’s wording addressed the ambiguity around how the stricture applies to format 4 (the stricture hadn’t been revised after format 4 was added to the spec); I added “of the same format” to Peter’s wording in the first sentence in order to address the main concern described in this email.
 
The last sentence of the proposal clarifies exactly what fields are being referred to in these strictures, based on feedback I received. For instance, we aren’t talking about the range axis value or the linked axis value.
 
 
=== Further thoughts ===
 
There have been some discussions about extending STAT to allow specifying range-based style linking, e.g. style-link anything in wght 350–450 to 700 (e.g. a bold-link button in an app), but this hasn’t been a space which folks seem to be very excited about. Apart from style-linking being seen by some as a legacy concept (despite those bold and italic “buttons” continuing to be central to important platforms), there is the question of whether it should be computationally round-trippable. Naturally the above model of range-to-one won’t allow for computational roundtripping; but even if we tried to specify a from-range and to-range for such a mapping, we’d need to specify how to evenly map the ranges when they are of different sizes, and precision/rounding behavior may cause some headaches. And if the solution to that is to say the document model/format should record the original value so that it could be “toggled” back to, well then computational round-trippability is not needed but rather a concept of “undo”, which the originally desired range-to-one model allows for just fine.
 
Thus, these efforts haven’t gained much traction, for the above and I’m sure other reasons. So apps will probably continue to do their own thing, especially with regard to style linking of variable fonts. At least we can cleanly allow for style linking of specific important instances in STAT, even if we leave style linking of the rest of the design space unspecified. That’s probably a good enough middle path.
 
===
 
John Hudson asked on OTFontVar whether app-side heuristics would be adequate for deriving instance names in the situations we’re talking about instead of specifying them in format 2 ranges (my paraphrase of some of his extensive comments).
 
Now, I can imagine if format 1 names are present for certain important points on the wght axis, then an app could change names midway between these points (and of course account for axis extremities as well). But this wouldn’t work in this version of Source Sans Variable:
 
Bold:
        \<NominalValue value="700.0"/>
        \<RangeMinValue value="650.0"/>
        \<RangeMaxValue value="750.0"/>
ExtraBold:
        \<NominalValue value="800.0"/>
        \<RangeMinValue value="750.0"/>
        \<RangeMaxValue value="800.0"/>
Black:
        \<NominalValue value="900.0"/>
        \<RangeMinValue value="800.0"/>
        \<RangeMaxValue value="900.0"/>
 
Can the designer/font producer be convinced in this specific instance to be satisfied with a midpoint or other heuristic instead, one that won’t yield the same results as the above format 2 ranges? Perhaps. But the point of the STAT table is to allow for the full creative expression of designers in specifying exactly how they want apps to display the names for various interesting parts of the design space.
 
Even if such a heuristic were adequate for wght, and even if all apps implemented that same heuristic, one must then ask whether apps should apply a midpoint or other heuristic to opsz names as well, instead of using the format 2 valueNameID fields for opsz in STAT. But format 2 valueNameID is specified as defining a “display string” not just for the nominal value but for the specified range.
 
Thus, we come back to the core issue of either STAT format 2 allows the designer to specify display names for a range or it doesn’t. The answer shouldn’t vary by axis. If format 2 was really intended only for opsz, STAT should have been designed differently (or the opsz info should have been added to the end of, say, the OS/2 table – just kidding! ;^).
 
(And this doesn’t even get into custom axes, and whether a midpoint heuristic would be adequate for them, which is a question difficult to answer given the nature of custom axes.)
 
===
 
There were other grander thoughts as well of reinventing the STAT table to allow for incrementally adding properties among formats (rather than adding a new format that was a combination of 2 and 3), but at this point I think removal or softening of the stricture as in the proposal above is the most practical way to move forward, given the situation. Yes there is the infelicity of specifying that the redundant flags and valueNameID must be the same (sentence 2 of the proposal), but for an OT table that’s now been in the works for about half a decade, that’s a small concession to make, all said and done!
 
Sairus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dac86fb-3792-6630-ade2-32bfc4bba93a
* Version Independent ID: 9de5c023-f363-3e42-43c9-eac7793c8eaa
* Content: [STAT — Style Attributes Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/stat#axis-value-tables)
* Content Source: [typographydocs/opentype/spec/stat.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/stat.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment] 2020-09-01 15:53
This issue is subsumed by an issue opened in the public typography-issues repo:
https://github.com/MicrosoftDocs/typography-issues/issues/576

So, closing this and tracking OT issues in the other repo.

**Comment by PeterCon** [comment] 2020-09-01 21:12
This pertains to a proposal discussed in a June 2019 OT meeting. See [Proposal](https://drive.google.com/file/d/1QdTp9kSZFcfMqovn0z0EmN4xJWx6Tz8s/view). No outcome was recorded in the OT [meeting notes](https://docs.google.com/document/d/1fV___desnqeofSejfbyovJ_hWmYeaem7n4nhIJPwl6U/edit#heading=h.g1afvn5omrbl). (Unclear if it got discussed.)

**Comment by PeterCon** [comment] 2020-09-16 23:26
Summarizing some of the history:

-	In 2016 when we created STAT, we decided to have an axis-value format that could provide style-linking information, which could help in particular for existing “B” and “I” user interfaces.
-	In 2016, we independently decided to have an axis-value format that could define ranges, particularly with (non-variable) optical size in mind—though it was never suggested that it could only be used for opsz.
-	The original intent for this guidance… 

“No two tables of the same format should provide information for the same axis value”

was to avoid potential ambiguity. For example, a font could include two axis value tables for the same value but with different name IDs, thereby creating ambiguity. Now, the wording “same axis values” has been read by some to not apply to format 2 and format 3 since they have different fields. However, the original intent was that no two axis value should have the same _value_ or _nominalValue_ for the same axis. (Otherwise, you could get Format2.value == Format3.nominalValue but Format2.nameID != Format3.nameID.)

-	In 2016, we didn’t anticipate any particular need to have axis-value tables that could provide _both_ style-linking _and_ range information.
-	Since then, some font developers have thought it might be useful to provide style-linking _and_ range information for the same axis value, and have added both format 2 and format 3 tables for the same (nominal) value, based on one reading of the current spec.


It seems to me there are three possible options:

1)	Revise the text of the STAT table to clearly sanction having both format 2 and format 3 tables for the same (nominal) value, but indicating they must have the same nameID.

2)	Revise the text to make clear that combining format 2 and format 3 tables should _not_ be done, but define a new format that provides both range and style linking info for a given axis value.

3)	Revise the text to make clear that combining format 2 and format 3 tables should _not_ be done, and _do nothing_ to accommodate providing both range and style linking info for the same axis value.

Re option 2, Adobe provided a draft proposal in the past, but it IIRC it came when most were busy with other matters and so never got much discussion. Sairus’ earlier comment reflects this:

> this hasn’t been a space which folks seem to be very excited about

Also, option 2 would have the issue that it would require software changes to support the new format, which will involve some latency. That shouldn’t stop us, however, if that’s what would be best long term.

Some things that pertain to both option 2 and option 3:

-	On the one hand, the whole style-linking user experience: on the one hand, it the “B” and “I” affordances and associate keyboard shortcuts are ubiquitous. 
-	On the other hand, variable fonts introduce many more variables into the scenario (or, more precisely, many more variable values), which makes it much less clear what a good style-linking UX design should be when variable fonts are involved.

Because of the latter point, it’s not entirely clear what additional information would be needed to make for a good style-linking UX design, with or without involving ranges. That might argue against #2, and maybe even suggest that the Format 3 table isn’t really sufficient even if ranges aren’t used.


I’ve discussed this with Sairus, and he indicated Adobe would be open to any of these options. They (and I) would just like to move it to closure.

Either option 1 or option 3 are relatively easy changes to make in the spec. Neither completely solve style-linking, but at least 3 is explicit about that, as well as sticking to the original intent to avoid ambiguity in tables.

**Comment by PeterCon** [comment] 2020-09-18 15:14
The original intent of

>No two tables of the same format should provide information for the same axis value

was to avoid ambiguity: e.g. two format 1 tables, or a format 1 and format 3 table, for the same tag/value but different name IDs. It was intended to apply also to a format 2 table with nominalValue the same as a format 1 or format 3 value.

But the spec has not made combining format 2 and format 3 invalid, and existing fonts have made use of combining the information provided in each. If the spec clarified that the name IDs should be the same, the ambiguity issue can be avoided that way. So, as long as there are no other concerns voiced, clarifying the text to sanction this would be a reasonable option.

I've sought from various sources. I've not heard any concerns with this option, and have heard affirmative support for this option.

Based on that input, here's a proposed revision for the next version:

>No two tables should provide information for the same <del>axis value.</del><ins>combination of axis values.</ins>
>
>* <ins>There should not be a format 1 table with tag and value that match the tag and nominal value of a separate format 2 table, or that match the tag and value of a separate format 3 table.</ins>
>* <ins>Since format 2 and format 3 each provide additional and distinct information associated with an axis value, a font may contain a format 2 table and a format 3 table with the same tag where the format 2 nominal value is the same as the format 3 value. The valueNameID of the two tables must be the same.</ins>
>* <ins>A format 4 table may specify an axis value that is also specified in another table, but only if there is some other difference in the combination of axis values specified by those two tables.</ins>

**Closed by PeterCon** 2020-09-18 15:14 UTC
Labels: OpenType spec, Priority 1

**Comment by sairuspatel** [comment] 2020-09-24 00:32
@PeterCon:
1.
I was wondering if we should add the following to the first bullet item in your proposal (previous comment):
 
“, or that match the tag and value of a format 4 table that has an axis count of 1.”
 
This came to mind because of Laurence’s observation that format 4 can currently express format 1. I haven’t been thinking of format 4 in that way, since the spec is clear about its intended use for “multi-axis value combinations associated with non-analytic name elements” (emphasis mine). Still, I see no requirement for format 4 axisCount to actually be > 1. Resolving this ambiguity is needed before my edit proposed above can be considered.
 
Perhaps you already took my point above into consideration in your wording of your 3rd bullet, because you didn’t mention the format of “another table” (could be 4 or could be 1–3, is an interpretation, and “combination” could technically reduce to even a single axis). But I wasn’t sure.
 
2.
In your second bullet, I think the last sentence should include a requirement for the flags field to be the same as well.
 
3.
(minor) Instead of “tag” in your bullets (and in my potential edit in 1 above), perhaps use “axis index” or simply “axis”. I don’t see “tag” used in this indirect way in the rest of the Axis Value Tables section. I’m fine with whatever you end up choosing, since this is minor.

**Comment by PeterConstable** [comment] 2020-09-24 06:16
Revised draft based on review feedback:

>No two tables should provide information for the same <del>axis value.</del><ins>combination of axis values:</ins>
>
>* <ins>There should not be a format 1 table with axisIndex and value that match the axisIndex and nominal value of a separate format 2 table, or that match the axisIndex and value of a separate format 3 table, or that match the axisIndex and value in a format 4 table that has an axis count of 1.</ins>
>* <ins>Since format 2 and format 3 each provide additional and distinct information associated with an axis value, a font may contain a format 2 table and a format 3 table with the same axisIndex where the format 2 nominal value is the same as the format 3 value. The flags and valueNameID of the two tables must be the same.</ins>
>* <ins>A format 4 table may specify an axis value that is also specified in another table, but only if there is some other difference in the combination of axis values specified by those two tables. In the case of a format 4 table with an axis count of 1, there should be no other axis value table for the same axis value (or nominal value).</ins>
