### ISSUE TITLE
Mismatch in script tags for "Universal Shaping" and regular Opentype script tags.

### ISSUE THREAD

**Issue by schriftgestalt** [MicrosoftDocs/typography-issues#1117] opened 2024-01-20 13:20 UTC
e.g. "Nag Mundari nagm" and "Kawi kawi" are present in the USE page but not here: https://learn.microsoft.com/en-us/typography/opentype/spec/scripttags

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://learn.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Service: **typography**
* GitHub Login: @Anglass
* Microsoft Alias: **anglass**

**Comment by PeterCon** [comment] 2024-01-23 06:33
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

This is a duplicate of #948, so closing.

**Closed by PeterCon** 2024-01-23 06:33 UTC
Labels: OpenType spec
