### ISSUE TITLE
Type of hdmx header fields

### ISSUE THREAD

**Issue by emuller-amazon** [MicrosoftDocs/typography-issues#190] opened 2019-03-11 00:47 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4696c9e-e34d-71cd-391b-900eb2d2df1a
* Version Independent ID: 415f8087-1bae-4b27-8646-1620f1e3cade
* Content: [hdmx - Horizontal Device Metrics - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/hdmx)
* Content Source: [typographydocs/opentype/spec/hdmx.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/hdmx.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by v-nihar** [comment] 2019-03-11 17:10
Closing as duplicate of 189.

**Closed by v-nihar** 2019-03-11 17:10 UTC
Labels: OpenType spec
