### ISSUE TITLE
Furthur explanation about `ARGS_ARE_XY_VALUES`?

### ISSUE THREAD

**Issue by DaseinPhaos** [MicrosoftDocs/typography-issues#805] opened 2021-07-29 05:52 UTC
The documentation around flag `ARGS_ARE_XY_VALUES` seems confusing for a TrueType newbee like me:

> Argument1 and argument2 can be either x and y offsets to be added to the glyph (the ARGS_ARE_XY_VALUES flag is set), or two point numbers (the ARGS_ARE_XY_VALUES flag is not set). In the latter case, _the first point number indicates the point that is to be matched to the new glyph. The second number indicates the new glyph’s “matched” point_.

What is the meaning of this point matching stuff?
The documentation seems to provide no further explanation, while reference implementations I found ([stb_truetype](https://github.com/nothings/stb/blob/master/stb_truetype.h) or [ttf_pars.rs](https://github.com/RazrFalcon/ttf-parser/blob/master/src/tables/glyf.rs) ) simply <s>ignores the flag</s>(*edit) applies no offset if the flag is unset.

Could the document provide further explanation or references about this flag? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a9a6a1-a9b9-0864-8982-322da821389e
* Version Independent ID: a42612e3-dc1d-f980-fe4a-4880d1fd0086
* Content: [glyf - Glyf data table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf)
* Content Source: [typographydocs/opentype/spec/glyf.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/glyf.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by Lorp** [comment] 2021-07-29 13:14
Indeed this part of the spec is inadequate. Here’s how to think about it:

We are converting a composite glyph into a fully decomposed simple glyph, let’s call it DecompGlyph. The composite glyph is represented as a tree of arbitrary depth, with simple glyphs at the leaf nodes. Initially DecompGlyph has no points. We parse the tree recursively, depth first, appending simple glyphs (when we find them at leaf nodes) to DecompGlyph. If we are in “matched points” mode, i.e. ARGS_ARE_XY_VALUES = 0, then the position of the appended simple glyph is determined by moving the glyph’s points, such that its points[args[1]] is at the same position as DecompGlyph’s points[args[0]]. So, args[1] is the point index of the simple glyph at the leaf node, and args[0] is the point index of the decomposed glyph being constructed. No phantom points are involved or counted in the conversion.

**Comment by DaseinPhaos** [comment] 2021-07-29 14:49
> Indeed this part of the spec is inadequate. Here’s how to think about it:
> 
> We are converting a composite glyph into a fully decomposed simple glyph, let’s call it DecompGlyph. The composite glyph is represented as a tree of arbitrary depth, with simple glyphs at the leaf nodes. Initially DecompGlyph has no points. We parse the tree recursively, depth first, appending simple glyphs (when we find them at leaf nodes) to DecompGlyph. If we are in “matched points” mode, i.e. ARGS_ARE_XY_VALUES = 0, then the position of the appended simple glyph is determined by moving the glyph’s points, such that its points[args[1]] is at the same position as DecompGlyph’s points[args[0]]. So, args[1] is the point index of the simple glyph at the leaf node, and args[0] is the point index of the decomposed glyph being constructed. No phantom points are involved or counted in the conversion.

Thanks for the detailed explanation. It makes much more sense for me now!

Also I just noticed that there is an [existing issue](https://github.com/MicrosoftDocs/typography-issues/issues/769) addressing the same concern about the document, so I'm closing this issue as a duplicate

**Comment by Lorp** [comment] 2021-07-29 15:03
Note that in variable fonts, the positions of both points may have changed. The points must be matched at their “live” positions, not their default positions. This note should probably also be added to the spec.

**Comment by PeterCon** [comment] 2021-10-20 18:58
Expected behaviour for both values of this flag need to be clarified. Details provided by @Lorp are helpful.

IIUC...

* If set, vector (x,y) = (arg1, arg2) is added to each control point of the component glyph indicated by glyphIndex.

* If not set, the component glyph `glyphIdex` is positioned such that a point (arg2) from the component glyph is aligned to a point (arg1) from previously incorporated glyphs (with points renumbered). However, it's not entirely clear whether arg2 is a point number _before or after_ the points are renumbered. The current wording seems to suggest before (points are renumbered "Once a glyph is added"), though that should be made clearer.

**Comment by Lorp** [comment] 2021-10-21 00:29
_arg2_ is definitely the point number in the glyph to be added, before renumbering.

**Comment by simoncozens** [comment] 2021-11-12 13:36
Typo in the new version:

> sequence of compoent glyph information

**Comment by PeterCon** [comment] 2021-12-09 00:40
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.

**Closed by PeterCon** 2021-12-09 00:40 UTC
Labels: OpenType spec

**Comment by waruyama** [comment] 2023-11-24 07:46
I have yet to find a font that actually uses glyf point numbers. If anyone knows of such font,this information would be very helpful for testing.

**Comment by moyogo** [comment] 2023-11-25 08:59
@waruyama Very few fonts do so likely because very few font authoring tools can generate fonts with the flag. See for example https://github.com/moyogo/molengo-fonts/releases/tag/v0.10

**Comment by Lorp** [comment] 2023-11-25 11:26
Discussion and a cool test font here https://github.com/Lorp/samsa/issues/55
