### ISSUE TITLE
Document distance type 3 (MDRP[], MIRP[], ROUND[], NROUND[])

### ISSUE THREAD

**Issue by lemzwerg** [MicrosoftDocs/typography-issues#237] opened 2019-05-21 04:57 UTC
The documentation correctly states that only values 0 (gray), 1 (black), and 2 (white) are valid for the distance type.  I suggest to define value 3 also, namely to be equal with value 0.  Reasons are as follows.

  * The specification doesn't explicitly say that value 3 is invalid.
  * Undefined opcodes are not optimal IMHO.
  * Both the MS engine (confirmed by Greg Hitchcock) and FreeType handle value 3 as equal to value 0.  I guess that the current version of Apple's engine does the same.

It might be worthwhile to consider whether value 3 should be equivalent to 'don't apply any distance type correction'.  Note that de-facto this is already the reality, since 'gray distance type' already implies zero correction for the MS engine (and FreeType, too, which sets all distance type compensations to zero).  If we go this route, the instruction `NROUND[3]` officially becomes a no-op.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb69554-e257-e483-2e26-7f04fdf44fd8
* Version Independent ID: d560a11c-2ac5-1abc-7165-453c3a9618c8
* Content: [The TrueType Instruction Set - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/tt_instructions)
* Content Source: [typographydocs/opentype/spec/tt_instructions.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/tt_instructions.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by PeterCon** [comment] 2020-09-05 19:34
This is an incomplete proposal:
- it doesn't suggest how value 3 should be succinctly referred to
- it doesn't suggest specific parts of the spec where a change would be required
- it leaves an open issue, "It might be worthwhile to consider..."

Regarding the second point, changes would be needed in descriptions of the four instructions mentioned in the title, but presumably there would also be changes required elsewhere, e.g. in the Instructing TrueType Glyphs chapter. (Anywhere else?) And what exactly should be said?

**Comment by PeterCon** [comment] 2021-11-05 18:35
For OT 1.9, the following addition to [The TrueType Instruction Set](https://docs.microsoft.com/en-us/typography/opentype/spec/tt_instructions) is proposed:

>For the three instructions sensitive to distance types, two bits of the opcode are used to determine the type. For these two bits, the values 0 (grey), 1 (black) and 2 (white) are used. The two bits allow for a fourth value, 3, which is not used. Some implementations treat this as type 1, while other implementations treat this as an error. Fonts must not specify distance type 3 for these instructions.

**Comment by lemzwerg** [comment] 2021-11-05 18:56
LGTM.  I just wonder why you say 'some implementations treat this as type 1', where I would expect 'type 0'...

**Comment by PeterCon** [comment] 2021-11-05 20:59
You're right: type 0 was intended. Thanks for spotting that.

**Comment by PeterCon** [comment] 2021-12-09 00:29
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.

**Closed by PeterCon** 2021-12-09 00:29 UTC
Labels: OpenType spec
