### ISSUE TITLE
Visual TrueType is no longer licensable

### ISSUE THREAD

**Issue by fitojb** [MicrosoftDocs/typography-issues#89] opened 2018-09-19 20:24 UTC
The very last paragraph of the page says:
> Type designers can license our Visual TrueType (VTT) font hinting tool […]

VTT used to be a commercial tool, but Microsoft made it free-to-use years ago. Instead of the verb “license” I would use “download” or simply “use”:

> Type designers can *use* our Visual TrueType (VTT) font hinting tool […]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2300b8-71e0-a6fe-b12f-f47b2b9564c1
* Version Independent ID: e771c103-3be0-7747-0084-be7bdef7bf63
* Content: [Microsoft ClearType - Typography](https://docs.microsoft.com/en-us/typography/cleartype/)
* Content Source: [typographydocs/cleartype/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/cleartype/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment] 2019-02-22 17:47
Closing as by design.

**Closed by v-nihar** 2019-02-22 17:47 UTC

**Comment by v-nihar** [comment] 2019-02-22 22:01
The install package for VTT requires the user to agree to the license agreement contained in the package.

**Comment by fitojb** [comment] 2019-02-24 22:18
That is not what the verb “license” denotes at all, but I’m not playing the semantics game with you.
