### ISSUE TITLE
Mismatch between pdf bookmark and the linked page

### ISSUE THREAD

**Issue by lie-yan** [MicrosoftDocs/typography-issues#851] opened 2021-10-31 22:59 UTC
On the **[Microsoft Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/math)** pages, the pdf file for [Download PDF](https://docs.microsoft.com/en-us/typography/opbuildpdf/toc.pdf?branch=live) link contains a few mismatches between bookmarks and the linked target, eg. "OpenType spec/Tables/MATH" points to the page for "OpenType spec/Tables/loca".

**Comment by PeterCon** [comment] 2021-11-02 05:21
I can't replicate the issue. Can you please clarify the steps you took?

**Comment by lie-yan** [comment] 2021-11-02 21:41
Sure. Click the "Download PDF" link, open the bookmark sidebar, click "OpenType spec > Tables > MATH". The current page switch to "... > loca" instead of "... > MATH".

Here is the snapshot.
<img width="1552" alt="Screen Shot 2021-11-03 at 5 37 18 AM" src="https://user-images.githubusercontent.com/7057802/139955659-9a52b0cb-a40b-4143-8280-d4ed52142f72.png">

**Comment by PeterCon** [comment] 2021-11-03 02:25
Thanks. I hadn't understood that the issue is with the PDF's table of contents metadata. I can repro this now.

**Comment by PeterCon** [comment] 2022-09-17 05:35
This issue appears to be fixed. Closing.

**Closed by PeterCon** 2022-09-17 05:35 UTC
