### ISSUE TITLE
Typo in fsType section

### ISSUE THREAD

**Issue by DLasher106** [MicrosoftDocs/typography-issues#1154] opened 2024-05-13 02:57 UTC
A typo in the comments for fsType

> Bits 0 to 3 (the embedding permissions sub-field) are mutually exclusive: fonts should never have **more than of these** bits set. 

The word “one” is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae9457c-0d3d-c137-588b-81d54a086f07
* Version Independent ID: 658c6d22-b9d1-1007-9cdb-6898911c9c75
* Content: [OS/2 - OS/2 and Windows metrics table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/os2#fsselection)
* Content Source: [typographydocs/opentype/spec/os2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/os2.md)
* Service: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment] 2024-05-14 17:44
This is a duplicate of #903, already fixed for OpenType 1.9.1. See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Closed by PeterCon** 2024-05-14 17:44 UTC
Labels: OpenType spec
