### ISSUE TITLE
Add content docs

### ISSUE THREAD

**Issue by davelab6** [MicrosoftDocs/typography-issues#73] opened 2018-08-27 14:47 UTC
Readme says,

> Currently the Microsoft Typography content docs are held in a private repo and are not accepting public contributions.

I would love to see the OT spec text itself be available in markdown on GitHub, so that the community can help provide improvements and context.

**Comment by v-nihar** [comment] 2019-02-22 17:46
Closing as be design.

**Closed by v-nihar** 2019-02-22 17:46 UTC

**Comment by alerque** [comment] 2020-06-23 13:34
This issue needs to be revisited. By _not_ doing this by design Microsoft is putting the lie to the "Microsoft loves Open Source" marketing mantra.
