### ISSUE TITLE
'frac' is unclear

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#580] opened 2020-09-01 21:34 UTC
> _Application interface:_ \[...] When the 'frac' table does not contain an exact match, the application performs two steps. First, it uses the 'numr' feature to replace figures (as used in the ['numr'](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko#numr) coverage table) preceding the slash with numerators, and to replace the typographic slash character (U+002F) with the fraction slash character (U+2044).  Second, it uses the ['dnom'](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#dnom) feature to replace all remaining figures (as listed in the 'dnom' coverage table) with denominators.

The description of 'frac' does not define “figures”. If a figure is whatever is in the coverage tables of 'numr' and 'dnom', then there are actually two definitions of “figure”, since different glyphs could be in the different coverage tables.

The description of 'frac' defines “slash” by its Unicode code point. That implies that an application must associate a code point with each glyph so it can check whether each glyph’s code point is U+002F. Is that the intent? If so, it needs to be defined how the various GSUB lookup types affect glyphs’ code point mappings. Or perhaps a “slash” is a glyph that 'cmap' maps U+002F to. That is simpler to implement but means a slash might not correspond to U+002F in the selected string if multiple code points map to that glyph.

What should the application do if the font’s 'cmap' does not cover U+2044? Or is it up to the font to map U+002F to U+2044 in 'numr'? If so, the application need not know anything about U+2044; this belongs in the “Recommended implementation” section for font producers, not the “Application interface” section for font consumers.

What should the application do if there is not exactly one slash in the selected string?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb16259e-1f7c-4e96-02b8-f692eb3e77e7
* Version Independent ID: eab1b2c5-0209-ccdf-b898-bbc5b5dbbe0f
* Content: [Registered features, f-j - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_fj)
* Content Source: [typographydocs/opentype/spec/features_fj.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_fj.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by khaledhosny** [comment] 2020-09-02 05:46
It should be also noted that there are probably no existing implementations that do what this text is describing.

**Comment by mikeday** [comment] 2020-09-02 05:48
I just implemented frac support recently for Allsorts and I have to say the documentation was highly misleading. :laughing:

**Comment by khaledhosny** [comment] 2020-09-02 06:01
In HarfBuzz, for example, when `frac` is enabled manually it just applies it's lookups like any other feature. 

Additionally, when there a fraction slash (U+2044) in input text, it enables `numr` for any sequence of numbers before the slash, and `dnom` to any squence of numbers after the slash, and `frac` to the whole lot. I’m not aware of any other implementations that do this kind of automatic fraction handling, though.

**Comment by mikeday** [comment] 2020-09-02 06:15
We need to support the CSS property `font-variant-numeric: diagonal-fractions` so we handle that by looking for text that matches the regexp `[0-9]+/[0-9]+` and applying the `frac` feature to those subranges of the glyph buffer along with all the other features that would normally apply in lookup order.

I tried applying `numr` and `dnom` to the fraction components but couldn't find any fonts where it helped! All the fonts I tested support the `frac` feature contextually by turning digits into their numerator forms unless they follow the slash or another denominator digit in which case they also turn into denominator form.

Some fonts like Arno Pro try to be clever and apply `frac` to more than just digits, so you can do complex fractions like -1/(2+3) or similar and it will actually work, but supporting that would require checking the feature coverage in the font otherwise the fraction might appear broken and the user agent won't know, so we stuck to basic digits for safety (the user can always manually apply the features if they know what they are doing).

**Comment by khaledhosny** [comment] 2020-09-02 13:37
This getting a bit off-topic, but anyway:

> We need to support the CSS property `font-variant-numeric: diagonal-fractions` so we handle that by looking for text that matches the regexp `[0-9]+/[0-9]+` and applying the `frac` feature to those subranges of the glyph buffer along with all the other features that would normally apply in lookup order.

This does not seem to mach how browsers handle it. Firefox, Chrome and Safari all apply `frac` unconditionally when `font-variant-numeric: diagonal-fractions` is used (and none of them does any `numr`/`dnom` fallback).

> I tried applying `numr` and `dnom` to the fraction components but couldn't find any fonts where it helped! All the fonts I tested support the `frac` feature contextually by turning digits into their numerator forms unless they follow the slash or another denominator digit in which case they also turn into denominator form.

https://github.com/alif-type/amiri has `numr` and `dnom` but not `frac`.

> Some fonts like Arno Pro try to be clever and apply `frac` to more than just digits, so you can do complex fractions like -1/(2+3) or similar and it will actually work, but supporting that would require checking the feature coverage in the font otherwise the fraction might appear broken and the user agent won't know, so we stuck to basic digits for safety (the user can always manually apply the features if they know what they are doing).

I don’t include `frac` feature exactly because of this, to support arbitrary fraction with `frac` one has to implement complex contextual substitution rules, while with `numr` and `dnom` it is up to application/user to decide what range of charcaters to apply the feature to.

**Comment by khaledhosny** [comment] 2020-09-02 13:40
> Firefox, Chrome and Safari all apply `frac` unconditionally

This makes difference if the `frac` lookups cover also, say, alphabetic letters or symbols.

**Comment by khaledhosny** [comment] 2020-09-02 13:52
> Additionally, when there a fraction slash (U+2044) in input text, it enables `numr` for any sequence of numbers before the slash, and `dnom` to any sequence of numbers after the slash, and `frac` to the whole lot. I’m not aware of any other implementations that do this kind of automatic fraction handling, though.

Just to be clear, this happens automatically if `frac` feature was not explicitly enabled (otherwise it is applied unconditionally), and it is to enable the Unicode-specified behavior of the fraction slash. From [TUS](https://www.unicode.org/versions/Unicode13.0.0/ch06.pdf):

> **_Fraction Slash_**. U+2044 fraction slash is used between digits to form numeric fractions, such as 2/3 and 3/9. The standard form of a fraction built using the fraction slash is defined as follows: any sequence of one or more decimal digits (General Category = Nd), followed by the fraction slash, followed by any sequence of one or more decimal digits. Such a fraction should be displayed as a unit, such as ¾ or [3/4]. The precise choice of display can depend on additional formatting information.

**Comment by tiroj** [comment] 2020-09-02 16:44
The frac feature description is as originally published, and doesn't reflect how the frac feature is commonly implemented. As described, it required software to perform something like complex script shaping string analysis to identify the different parts of a fraction sequence and then apply appropriate numr or dnom features discretely. This is unnecessary, because numerator and denominator substitutions can be handled contextually at the GSUB level, within a single feature, which is what everyone making fonts has been doing since I first proposed it to the OT mailing list c.20 years ago.

Since numerator and denominator forms are specific to fractions, I wish the numr and dnom features could be deprecated. I can't think of a situation in which one would want to apply either of these features instead of just using the frac feature. However, Adobe InDesign has actual UI controls for these features, so a lot of font makers continue to implement them in fonts, alongside the typical contextual frac feature implementation.

**Comment by khaledhosny** [comment] 2020-09-02 16:55
I think `numr` and `dnom` are good for supporting arbitrary fractions without having to do contextual substitutions that `frac` require.

**Comment by behdad** [comment] 2020-09-02 21:45
> I think `numr` and `dnom` are good for supporting arbitrary fractions without having to do contextual substitutions that `frac` require.

+1. Would be a mistake to deprecate them.

**Comment by tiroj** [comment] 2020-09-02 22:29
In that case the feature descriptions still need to be revised to reflect actual implementation. Given how HarfBuzz uses them, I suggest making their use with U+2044 explicit in the implementation recommendations, as well as pointing out that this is independent of the frac feature, which commonly implements numerator and denominator substitutions within its own contextual GSUB lookups.

**Comment by PeterCon** [comment] 2021-11-03 05:23
One thing not clear to me: If fonts commonly implement 'frac' by applying some set of substitutions over the numerator + slash + denominator sequence, then what is thought to be different between 'frac' and 'afrc'?

**Comment by PeterCon** [comment] 2021-11-03 05:36
Proposed revisions for OT 1.9:

>*Friendly name:* Fractions
>
>*Registered by:* Microsoft/Adobe
>
>*Function:* Replaces figures (digits) separated by a slash (U+002F<ins> or U+2044</ins>) with “common” (diagonal) fractions.
>
>*Example:* The user enters 3/4 <del>in a recipe </del>and gets the threequarters fraction.
>
>*Recommended implementation:* Glyphs for figures (digits) separated by a slash <del>(U+002F) </del>are mapped to variant forms (GSUB lookup type 1, or contextual substitutions that reference type 1 lookups), or sequences of such glyphs are mapped to ligature fraction glyphs (GSUB lookup type 4).
>
>*Application interface:* <del>The application evaluates the sequence of glyphs for the span of characters over which this feature has been applied by the user. If an associated lookup subtable matches the entire glyph sequence, the substitutions described in that lookup are applied to the glyph sequence directly. If no lookup subtable is found that matches the entire sequence, then the application does the following:</del><ins>Discretionary feature: can be applied to glyph runs based on document markup, user control or other application criteria.</ins>
>
>* <del>Apply the [&#39;numr&#39;](features_ko.md#numr) feature to the figures within the span that precede the slash and also to the slash, and process associated lookups.</del>
>* <del>Apply the [&#39;dnom&#39;](features_ae.md#dnom) feature to the figures within the span that follow the slash and process associated lookups.</del>
>
><ins>An application may automatically apply the feature over certain text sequences, such as sequences of one or more digits followed by fraction slash (U+2044) followed by one or more digits. An application may also automatically apply the [&#39;numr&#39;](features_ko.md#numr) feature to a sequence preceding a slash, and the [&#39;dnom&#39;](features_ae.md#dnom) feature to a sequence following a slash, either based on analysis of the text sequence or as a corollary to application of the &#39;frac&#39; feature over a sequence.</ins>
>
>*UI suggestion:* This feature should be off by default.
>
>*Script/language sensitivity:* None.
>
>*Feature interaction:* <del>This feature may require the application to apply</del><ins>Applications may use this feature in conjuction with </ins>the [&#39;numr&#39;](features_ko.md#numr) and [&#39;dnom&#39;](features_ae.md#dnom) features. It may be used in combination with other substitution (GSUB) features, whose results it may override.

**Comment by tiroj** [comment] 2021-11-03 16:13
> One thing not clear to me: If fonts commonly implement 'frac' by applying some set of substitutions over the numerator + slash + denominator sequence, then what is thought to be different between 'frac' and 'afrc'?

Style of fractions. The 'afrc' feature was registered for ‘nut’ fractions, i.e. vertically stacked fractions with the numerator and denominator separated by a horizontal line, rather than diagonally arranged relative to a slanted slash (so called because, traditionally, such fractions in metal type were approximately en width (presuming a single numerator and denominator)).

As defined, the 'afrc' feature presumes ligature glyph outcomes, and as such is really only useful for common fractions with a single numerator and denominator. The vertical arrangement and need for the dividing line to stretch makes it very difficult for the nut fraction style to be applied via OTL to arbitrary fractions. The closest I have managed to come is the[ Nutso project](https://github.com/TiroTypeworks/Nutso), which works quite well so long as no tracking is applied to the sequence. That model was also used in the Myanmar Text project for Burmese fractions which are conventionally always vertically stacked.

**Comment by PeterCon** [comment] 2021-11-03 17:29
Ah! I missed the mention of "nut fraction" in the example field.

Curious: What would be expected if both features were applied to the same text? Or how would you handle that in a font that supported both?

**Comment by khaledhosny** [comment] 2021-11-03 18:12
> Curious: What would be expected if both features were applied to the same text? Or how would you handle that in a font that supported both?

Discretionary feature interaction is generally un/underdefined. For example what happens when both tnum and lnum features are turned on? Open type implementations I'm familiar with don't do anything special and most fonts don't either and probably the order of the lookups will determine the outcome. Some GUIs make such features mutually exclusive.

**Comment by tiroj** [comment] 2021-11-03 19:50
Yes, I would expect the outcome to be dependent on the lookup ordering and the inputs of the respective lookups. I’ve never actually implemented European nut fractions in any shipping fonts, only worked out the Nutso method and then applied that to Burmese fractions. A few years ago, Monotype contacted me to confirm that the Nutso license enabled them to implement the logic in some fonts they were working on, so they might have examples of fonts that implement both frac and afrc.

If I were making a font that implemented both, my approach would probably be to give preference to frac (order its lookups first) and require the user to independently apply afrc.

**Comment by kenmcd** [comment] 2021-11-04 21:39
A real world example...
Surveyor Text by Hoefler has both `afrc` (stacked) and `frac` (diagonal) arbitrary fractions.
`afrc` is pre-composed from 1/8 to 7/8 (incl. 1/4, 1/2, 3/4, 1/5, etc.)
Then `afrc` has arbitrary stacked fractions from 1/1 thru 99/99.
`ss06` is a duplicate of `afrc`.
Both `afrc` and `ss06` take precedence over `frac`  when both are enabled.
When `tnum` is enabled it disables `afrc`.
When `frac` is enabled `tnum` substitutes `fraction.tab` for `fraction`.

**Comment by PeterCon** [comment] 2021-12-09 00:30
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.

**Closed by PeterCon** 2021-12-09 00:30 UTC
Labels: OpenType spec
