### ISSUE TITLE
[OpenType] Language System Tags for languages using Greek characters in Latin alphabets

### ISSUE THREAD

**Issue by moyogo** [MicrosoftDocs/typography-issues#1037] opened 2023-05-04 20:09 UTC
Several languages use Greek characters in their Latin alphabets, one or several of α U+03B1, Δ U+0395, δ U+03B4, Θ U+0398, ϴ U+03F4, θ U+03B8, ϑ U+03D1, ꭓ U+03C7.
Please consider adding the following Language System Tag:
Language System | Language System Tag | Corresponding ISO 639 ID (if applicable)
-- | -- | --
Eastern Abenaki | 'AAQ ' | [aaq](https://iso639-3.sil.org/code/aaq)
Cypriot Arabic | 'ACY ' | [acy](https://iso639-3.sil.org/code/acy)
Atsina | 'ATS ' | [ats](https://iso639-3.sil.org/code/ats)
Comox | 'COO ' | [coo](https://iso639-3.sil.org/code/coo)
Halkomelem | 'HUR ' | [hur](https://iso639-3.sil.org/code/hur)
Straits Salish | 'STR ' | [str](https://iso639-3.sil.org/code/str)
Thompson | 'THP ' | [thp](https://iso639-3.sil.org/code/thp)
Tuscarora | 'TUS ' | [tus](https://iso639-3.sil.org/code/tus)
Wakhi | 'WBL ' | [wbl](https://iso639-3.sil.org/code/wbl)
Havasupai-Walapai-Yavapai | 'YUF ' | [yuf](https://iso639-3.sil.org/code/yuf)

Cypriot Arabic [acy] is an individual language part of the macrolanguage Arabic [ara] which already has a tag 'ARA '.
Romani [rom] already has the tag 'ROY ' and no change regarding it is being proposed here.

References:
- [aaq] [_Penobscot Dictionary_](https://penobscot-dictionary.appspot.com/entry/5370967467491328/), 2015
- [acy] Marilena Karyolemou, Spyros Armostis, ["Langue ancienne, écriture nouvelle : codification et standardisation de l’arabe de Chypre"](http://journals.openedition.org/cchyp/529), _Cahiers du Centre d’Études Chypriotes_, vol. 50, 2020
- [ats] Allan R. Taylor, [_Gros Ventre Dictionary_](https://ftbelknaplanguagepreservation.com/FBLPPDocuments.html), vol. 1-2, Gros Ventre Treaty Committee, 1994
- [coo] ["Sliammon alphabet"](https://www.firstvoices.com/explore/FV/sections/Data/Salish/Northern%20Salishan/Sliammon/learn/alphabet), _First Voices_
- [hur] Musqueam First Nation and MOA, ["hən̓q̓əmin̓əm̓ Alphabet"](https://www2.moa.ubc.ca/musqueamteachingkit/alphabet.php), _Musqueam Teaching Kit_
- [str] ["lək̓ʷəŋən Language Reawaken"](https://www.songheesnation.ca/community/l-k-ng-n-language-reawaken), _Songhees Nation_
- [thp] ["nłeʔkepmxcin alphabet](https://www.firstvoices.com/explore/FV/sections/Data/scw%CC%93exmxc%C3%8Cn/n%C5%82e%CA%94kepmxcin/n%C5%82e%CA%94kepmxcin/learn/alphabet), _FirstVoice.com_
- [tus] "[Nęyękwawętaʔθkwáhshek (We will carry on the language)](https://sites.google.com/tuscaroralanguage.org/ntlp)", _Nęyękwawętaʔθkwáhshek Tuscarora Language Program (NTLP)_
- [thp] ["nłeʔkepmxcin alphabet](https://www.firstvoices.com/explore/FV/sections/Data/scw%CC%93exmxc%C3%8Cn/n%C5%82e%CA%94kepmxcin/n%C5%82e%CA%94kepmxcin/learn/alphabet), _FirstVoice.com_
- [wbl] ["Wakhi alphabet"](https://wakhi.wordpress.com/about/), _X̌ik-Wakhi, Wakhi on the Roof of the World_, 2008 
- [yuf] Alan Shaterian, Pamela Munro, Martha B. Kendall, "Yavapai literature", _Spirit
Mountain: an anthology of Yuman story and song_, 1984, Tucson, Arizona : Sun Tracks and the
University of Arizona Press. p. [171](https://archive.org/details/spiritmountainan0010unse/page/171/mode/1up).

**Comment by tiroj** [comment] 2023-05-05 22:58
While I support addition of these langsys tags, the available mechanisms under OTL to display appropriate forms of Greek letters in Latin alphabets are neither reliable enough nor adequate for proper typography of these languages. 

Substitution of the correct glyphs for these characters based on langsys tags requires correct language tagging of document text, correct mapping of text language tagging to OTL langsys tags, and software support for related locl OTL features. These are not reliable mechanisms.

Even if these mechanisms work as intended and result in correct glyph forms, script itemisation by Unicode character property isolates Greek letters in Latin text context from neighbouring glyphs, preventing interaction such as kerning, which is critical in the writing of many indigenous orthographies of the Americas due to the high frequency of digraphs involving these letters.

We either needs specifically Latin characters to be encoded in Unicode for these Latin alphabet letters, or a mechanism to have them itemised as Latin characters for OTL processing, or a mechanism to enable cross-script interaction at some stage in OTL processing (as discussed in 2014 and 2015 OT ad hoc working group meetings).

**Comment by verdy-p** [comment] 2024-01-09 18:41
Consider also implementing the "dlng" metadata (Design language/script) correctly. It is already used in Windows 11: Settings>Fonts (in the font selector at top of the displayed list of installed fonts, and in displayed properties when we select a font).

One font in Windows (the only one propovided to support these scripts) is incorrect: "Ebrima" (v5.18)

**Comment by PeterConstable** [comment] 2024-02-16 20:51
@moyogo One thing you didn't state, but would be helpful to clarify: When those Greek letters are used in those (primarily-)Latin orthographies, are they typographically different from their use in Greek orthographies?

**Comment by PeterConstable** [comment] 2024-02-16 20:55
@moyogo Also, regarding Cypriot Arabic, you said,
>Cypriot Arabic [acy] is an individual language part of the macrolanguage Arabic [ara] which already has a tag 'ARA '.

Is Cypriot Arabic content likely to be language-tagged (BCP47) using "ara"? If so, would 'ARA ' suffice for any typographic distinction for Greek letters? (Btw, nothing constrains 'ARA ' being used only in conjunction with the script tag 'arab'.)

**Comment by moyogo** [comment] 2024-02-17 02:13
> @moyogo One thing you didn't state, but would be helpful to clarify: When those Greek letters are used in those (primarily-)Latin orthographies, are they typographically different from their use in Greek orthographies?

It depends, historically less so, recently more so but the different can be harder to spot in sans serifs.
For Cypriot Arabic the preference seems to be to preserve the Greek identity of the letters to some degree. For the others, the alphabets are not considered mixed script.

> Is Cypriot Arabic content likely to be language-tagged (BCP47) using "ara"? If so, would 'ARA ' suffice for any typographic distinction for Greek letters? (Btw, nothing constrains 'ARA ' being used only in conjunction with the script tag 'arab'.)

That works.

**Comment by PeterConstable** [comment] 2024-02-20 03:39
TUS also requested in #970.

**Comment by PeterCon** [comment] 2024-02-20 03:40
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment] 2024-05-16 17:14
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.

**Closed by PeterCon** 2024-05-16 17:14 UTC
Labels: OpenType spec
