### ISSUE TITLE
nameID 25: must be unique per font file

### ISSUE THREAD

**Issue by mekkablue** [MicrosoftDocs/typography-issues#1094] opened 2023-11-27 10:41 UTC
Please add a note for ID 25 that it is necessary or at least recommended that it be unique per font file.

Why does it need to be unique per font file? Because of [Adobe Tech Note 5902](https://adobe-type-tools.github.io/font-tech-notes/pdfs/5902.AdobePSNameGeneration.pdf), where it says: ‘If the font provides a Variations PostScript Name Prefix string (name ID 25), use that’. Imagine Roman and Italic having the same nameID 25, then we would risk a postcriptName conflict at equal slider positions (e.g. wght and wdth) between Roman and Italic.

**Comment by PeterConstable** [comment] 2024-01-22 04:30
@mekkablue: Do you mean per font _file_, or per font _family_?

**Comment by mekkablue** [comment] 2024-01-22 04:30
File.

**Comment by PeterConstable** [comment] 2024-01-22 06:44
Hmmm.... 

ATN 5902 specifies use of ID 25 in relation to a _family_ prefix, not a _face_ or _file_ prefix.

>First, create a **family** prefix for the PostScript name.
> 1. If the font provides a Variations PostScript Name Prefix string (name ID 25), use that.
> 2. Otherwise create the family prefix as follows:
a. Start with the US English string for typographic family name (name ID 16).
b. Remove any characters other than ASCII-range uppercase Latin letters, lowercase 
Latin letters, and digits
>
> To this **family** prefix, append the style information as follows.
> ...

(Emphasis added.) The alternative to name ID 25 (if not present) is to use name ID 16.

So, suppose a pair of variable fonts with family name "Foo", one Roman and one Italic, and both having a weight axis. The fonts in both files should have name ID 16 = "Foo". If name ID 25 isn't present, the ATN 5902 algorithm would construct PS names for instances from both fonts using "Foo", not "Foo" (or "FooRoman") for the one and "FooItalic" for the other.

However, it does appear that ATN 5902 is overlooking exactly this scenario. It _could_ appear to information in the STAT table. For example, in the example scenario, the italic "Foo" font should have a STAT table that includes info indicating that, within its typographic family, it has a distinguishing attribute of *Italic*. 

This needs some clarification from Adobe. Apple also makes some use of PS names and they may have thoughts.

**Comment by tiroj** [comment] 2024-01-22 17:31
Point of information: font makers are struggling with name ID 25 because of possibly broken implementation in Adobe InDesign that a) seems to require that variable fonts contain ID 25, regardless of whether they need them according to ATN 5902, and b) requires that they be unique and not shared between roman and italic fonts.

**Comment by Lorp** [comment] 2024-01-22 17:59
More commentary on [Type Drawers in August 2020](https://typedrawers.com/discussion/comment/48638), confirming it is "unique per file" that is required, not "unique per family".

@thlinard tested then-current Adobe apps and concluded "From my first tests nameID 25 + postscriptNameID in fvar is still needed, but [STAT] AxisValue format 2 is no longer needed."

**Comment by thlinard** [comment] 2024-01-24 09:18
Hi @Lorp 

I haven't done any comprehensive testing in a while, but VF support in InDesign is a moving target at the moment: InDesign 2024 may indicate that a variable font is missing when the axis value is outside a named instance (what I have observed with fonts whose STAT.AxisValue is in format 2). The Adobe development teams have had an internal ticket on this subject (ID-4245215) since November.

**Comment by PeterCon** [comment] 2024-02-19 23:31
@josh-hadley, can you please comment per our discussion last month?

**Comment by PeterConstable** [comment] 2024-02-19 23:50
> More nameID 25 commentary on [Type Drawers in August 2020](https://typedrawers.com/discussion/comment/48638), confirming it is "unique per file" that is required, not "unique per family".

What was confirmed was behaviour in certain apps, not what is correct in the spec. The original intent for name ID 25 was a _family_ prefix, not a _font-resource_ prefix.

(It definitely couldn't be _file_ prefix as that wouldn't work in a TTC.)

**Comment by josh-hadley** [comment] 2024-02-20 16:36
> @josh-hadley, can you please comment per our discussion last month?

> What was confirmed was behaviour in certain apps, not what is correct in the spec. The original intent for name ID 25 was a family prefix, not a font-resource prefix.

Right; the original intent of the spec seems to have been misunderstood or wrongly interpreted in some implementations. I and others at Adobe have been pressing for fixes in affected Adobe products (those fixes are in the works but I do not have an ETA on releases). In the meantime, the workaround of using a unique nameID 25 per VF ("resource" which could be a file, or font within a TTC) gets around the symptoms of the implementation bugs (provided the font is otherwise set up with complete and correct STAT table values, etc.).

**Comment by PeterCon** [comment] 2024-02-27 21:12
No further comments received. No spec changes are planned for this issue, so closing.

**Closed by PeterCon** 2024-02-27 21:12 UTC
Labels: OpenType spec
